#!/bin/bash
junit_version=1.12.2
app_name=$1
# create project folder structure
mkdir -p ${app_name}/{src/{docs,{main,test}/{java,resources/i18n}},libs}
# Add the README file
cat <<EOL > ${app_name}/README.md
# README

This is the readme file for the project ${app_name}

That's all folks !
EOL
# Add the internationalisation file
cat <<EOL > ${app_name}/src/main/resources/i18n/messages.properties
app.name=${app_name}
app.version=0.0.1
app.language=English
EOL
# Add the configuration file
cat <<EOL > ${app_name}/src/main/resources/config.properties
app.debug=0
app.mode=PROD
EOL
# Add .gitignore
echo """
target/
*.class
*.jar
*.war
*.ear
*.db
*.log
*.tmp
*.swp
*.swo
""" > ${app_name}/.gitignore
# Add main class
mkdir -p "${app_name}/src/main/java/core"
CAT <<EOL > "${app_name}/src/main/java/core/App.java"
package core;
import java.io.IOException;
import java.time.ZonedDateTime;
import java.util.Locale;
import java.util.Properties;
import java.util.ResourceBundle;

public class App {

  public enum Mode {
    DEV, TEST, PROD;
  }

  public enum LogLevel {
    DEBUG, INFO, WARN, ERROR;
  }

  private static final ResourceBundle messages = ResourceBundle.getBundle(\"i18n/messages\", Locale.ROOT);
  private static final Properties config = new Properties();
  private static String configFileName = \"config.properties\";

  private static int debug = 0;
  private Mode mode = Mode.PROD;

  public App() {
    log(App.class, LogLevel.INFO, \"%s (%s)\".formatted(
    	messages.getString(\"app.name\"), 
    	messages.getString(\"app.version\")));
    log(App.class, LogLevel.INFO, \"Language: %s\".formatted(
    	messages.getString(\"app.language\");));
    log(App.class, LogLevel.INFO, \"Starts...\");

  }

  public void run(String[] args) {
    initConfig();
	parseArguments(args);
    configFileName = config.getProperty(\"configFileName\");
    loadConfig(configFileName);
	parseArguments(args);
    parseConfig();
    log(App.class, LogLevel.INFO, \"End.\");
  }
  
  private void initConfig() {
    // set default values
    config.setProperty(\"app.debug\", \"0\");
    config.setProperty(\"app.mode\", \"PROD\");
    config.setProperty(\"configFileName\", \"config.properties\");
  }

  private void loadConfig(String fileName){
      // load values from configuration file
    try {
      config.load(this.getClass().getResourceAsStream(fileName));
      // extract values
    } catch (IOException e) {
      log(App.class, LogLevel.ERROR, \"Unable to read configuration from file '%s' : %s%n\", fileName, e.getMessage());
    }
  }

  private void parseConfig() {
    for (String key : config.stringPropertyNames()) {
      switch (key) {
		  case \"app.debug\", \"debug\" -> {
		    int debug = Integer.parseInt(config.getProperty(key));
		    log(App.class, LogLevel.INFO, \"- debug: %d\", debug);
		  }
		  case \"app.mode\", \"mode\", \"m\" -> {
		    this.mode = Mode.valueOf(config.getProperty(key).toUpperCase());
		    log(App.class, LogLevel.INFO, \"- mode: %s\", mode);
		  }
		  default -> {

		  }
      }
    }
  }

  private void parseArguments(String[] args){
      for (String arg : args) {
      if (arg.contains(\"=\")) {
        String[] keyValue = arg.split(\"=\", 2);
        String key = keyValue[0];
        String value = keyValue[1];
        config.setProperty(key, value);
        log(App.class, LogLevel.INFO, \"Overridden config: %s=%s\", key, value);
      }
    }
  }

  public static void main(String[] args) {
    App app = new App();
    app.run(args);
  }

  public static boolean isDebugGreaterThan(int i) {
    return debug > i;
  }

  public static void log(Class<?> className, LogLevel level, String message, Object... args) {
    System.out.printf(\"%s;%s;[%s];%s%n\", ZonedDateTime.now(), level, className.getName(), message.formatted(args));
  }
}
EOL
# VS Code integration
mkdir -p ${app_name}/.vscode
cat <<EOL > ${app_name}/.vscode/settings.json
{
    \"java.format.settings.url\": \".vscode/java-formatter.xml\",
    \"java.project.sourcePaths\": [
        \"src/main/java\",
        \"src/main/resources\",
        \"src/test/java\",
        \"src/test/resources\"
    ],
    \"java.project.encoding\": \"warning\",
    \"java.project.referencedLibraries\": [],
    \"java.project.outputPath\": \"target/classes\"
}
EOL
cp ~/scripts/scripts-library/java-formatter.xml ${app_name}/.vscode/java-formatter.xml	

# Add docs
app_name=${app_name}
cat <<EOL > "${app_name}/src/docs/00-preface.md"
# Project ${app_name}

## Preface

This is the preface for the documentation of the project ${app_name}.
You must rewrite this document according to your specifications.

>[!NOTE]
>Please us the markdown text format to easily create 
>docs in multiple format with the 'pandoc' tool. 
EOL
# Add build script
cp ~/scripts/build-mini.sh ${app_name}/build
# Add junit library
curl -sL https://repo1.maven.org/maven2/org/junit/platform/junit-platform-console-standalone/${junit_version}/junit-platform-console-standalone-${junit_version}.jar >${app_name}/libs/junit-platform-console-standalone-${junit_version}.jar
# create local git repository
git init --initial-branch=main
git -C "${app_name}" add .
git -C "${app_name}" commit -m "Create the project '${app_name}'"
echo "Project '${app_name}' created."
