#!/bin/bash
# list all authors in commit of the current git repository 
# [nbcommit] [author name] [author email]
#
echo "#  | Author           | Email                   |" 
git log --format='| %aN | <%aE> |' | awk '{arr[$0]++} END{for (i in arr){print arr[i], i;}}' | sort -rn | cut -d ';' -f2-
