#!/bin/bash
# Usage:  script.sh <project_name>
app_name=$1
mkdir -p ${app_name}/{src/{{main,test}/{java,resources},docs},libs}
echo "#README" >${app_name}/README.md
echo "target/" >${app_name}/.gitignore
echo "java=24-zulu">.sdkmanrc

# Sources
mkdir -p ${app_name}/src/main/resources/i18n
mkdir -p ${app_name}/src/main/java/core
curl -sL https://gist.githubusercontent.com/mcgivrer/01728ce9e04d389c6a08a065c10cb1b5/raw/60c744849c477bcb8bc0dd03394e3bd931e05879/App.java >${app_name}/src/main/java/core/App.java
curl -sL https://gist.githubusercontent.com/mcgivrer/01728ce9e04d389c6a08a065c10cb1b5/raw/60c744849c477bcb8bc0dd03394e3bd931e05879/config.properties >${app_name}/src/main/resources/config.properties
curl -sL https://gist.githubusercontent.com/mcgivrer/01728ce9e04d389c6a08a065c10cb1b5/raw/60c744849c477bcb8bc0dd03394e3bd931e05879/messages.properties >${app_name}/src/main/resources/i18n/messages.properties
# Project documentation

echo """# Project ${app_name}

## Preface

This is the preface for the documentation of the project ${app_name}.
You must rewrite this document according to your specifications.

>[!NOTE]
>Please us the markdown text format to easily create 
>docs in multiple format with the 'pandoc' tool. 

""" > ${app_name}/src/docs/00-preface.md
# Dependencies
curl -sL https://repo1.maven.org/maven2/org/junit/platform/junit-platform-console-standalone/1.12.2/junit-platform-console-standalone-1.12.2.jar >${app_name}/libs/junit-platform-console-standalone-1.12.2.jar
# build
curl -sL https://gist.githubusercontent.com/mcgivrer/b95bf476b8494c180c0a386a5ae11264/raw/0618c582240ec4972fad844c884d28df086ab674/build >${app_name}/build
chmod +x ${app_name}/build
# Integrate VSCode support
mkdir ${app_name}/.vscode
echo """
{
	\"java.project.sourcePaths\":[
		\"src/main/java\",
		\"src/main/resources\",
		\"src/test/java\",
		\"src/test/resources\",
	  ],
	\"java.project.encoding\":\"warning\",
	\"java.project.referencedLibraries\":[
		\"libs/junit-platform-console-standalone-1.22.2.jar\"
 	  ],
	\"java.project.outputPath\":\"target/classes\"
}
""" >.vscode/settings.json
# build
curl -sL https://gist.githubusercontent.com/mcgivrer/b95bf476b8494c180c0a386a5ae11264/raw/0618c582240ec4972fad844c884d28df086ab674/build >${app_name}/build
# git repo
git init -b main --quiet ${app_name}/
git -C ${app_name} add .
git -C ${app_name} commit -m "Create Project ${app_name}"
echo "Project '${app_name}' created."

