#!/bin/bash
# New Java project script generation
# Version: 1.1
# Author: Frédéric Delorme <frederic.delorme@gmail.com>
# Date: 2025-08-29
# 
# This script creates a new Java project with a specified structure,
# including directories for source code, resources, tests, and documentation.
# It also initializes a Git repository, sets up a README file, and configures
# the project for use with VSCode and SDKMAN.
# This script is designed to be run in a Unix-like environment with bash.
#
# TEMPLATE DOCUMENTATION
# ======================
# This script supports generating Java application classes using customizable templates. Two main templates are provided:
# 
# App_template.java: A minimal application class with configuration, logging, and internationalization support.
# App_Frame_template.java: An extended version with a graphical window (JFrame), event handling, and drawing utilities.
# 
# But you can provide your own template with the -t,--template <MY_OWN_TEMPLATE> option in the CLI.
#
# Templating Workflow
# -------------------
# Template Variables
#
# The templates use placeholders such as 
#  - ${PROJECT_PACKAGE_NAME}, 
#  - ${PROJECT_MAIN_CLASS_NAME}, 
#  - ${PROJECT_NAME}, 
#  - ${GIT_AUTHOR_NAME}, 
#  - ${GIT_AUTHOR_EMAIL}, 
#  - and ${PROJECT_APP_VERSION}.
#
# These are replaced by the script with project-specific values.
# 
# Class Generation
# ----------------
# The script reads the selected template.
# It substitutes all placeholders with actual values from the project configuration or user input.
# The resulting Java file is saved in the appropriate package directory.
#
# ! Limitation  !
# The template engine is very simple and very limited, it will only replace tokens with values. No Loop, no confition.
#  
# Features
# --------
# App_template.java:
#  - Basic application lifecycle (init, run, dispose)
#  - Config file loading and argument parsing
#  - Logging (info, warn, debug, error)
#  - Internationalization via ResourceBundle
# App_Frame_template.java:
#  - All features of App_template.java
#  - GUI window creation (JFrame)
#  - Keyboard event handling
#  - Double-buffered rendering and text drawing utilities
#
# Happy Coding !
# McG.
#
# MIT License
# 
# Copyright (c) 2025 Frédéric Delorme <frederic.delorme@gmail.com>
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# 

# Fonction pour afficher l'utilisation du script
usage() {
    echo "Usage: $0 [-p <project_name>] [-j <java_version>] [-a <author_name>] [-e <author_email>] [-r <remote_repo_url>] [-f|--frame]  ..." 
    echo ""
    echo "Options:"
    echo " -p, --project <project_name>                Project name to create (default: myapp)"
    echo " -n, --name <application_name>               Application name (default: capitalized project name)"
    echo " -j, --java <java_version>                   Java version to use (default: 24-zulu)"
    echo " -a, --author-name <author_name>             Git author name (default: Default Author)"
    echo " -e, --author-email <author_email>           Git author email (default: default@example.com)"
    echo " -r, --remote <remote_repo_url>              Remote repository URL for push (optional)"
    echo " -pk, --package <PROJECT_PACKAGE_NAME>       Package name (default: core)"
    echo " -mc, --main-class <PROJECT_MAIN_CLASS_NAME> Main class name (default: App)"
    echo " -f, --frame                                 Create an application with a window (default: no)"
    echo " -t, --template <App_CLASS_TEMPLATE>         Path to the application template (optional)"
    echo " -vd,--vendorname <VENDOR_NAME>              Vendor name (default: Vendor_name)"
    echo " -h,-?,--help                                Show this help"
    echo ""
    echo "Example:"
    echo ""
    echo "$0 -p my_project -n MyProject -j 17-zulu \\"
    echo " -a \"John Doe\" -e \"john.doe@mymail.com\" \\"
    echo " -r \"https://github.com/jdoe/my_git_project.git\" \\"
    echo " -pk \"com.core.demo\" -mc \"ApplicationDemo\" \\"
    echo " -f -vd MyOwnCompany"
    echo ""
    echo "This command line will create a java project based on java 17, "
    echo "named 'my_project' containing a main class 'com.core.demo.ApplicationDemo'"
    echo "with a JFrame application and the application name displayed will be 'MyProject'."
    echo "---"
    echo ""
    exit 1
}

# Valeurs par défaut
export APPLICATION_NAME=
export PROJECT_NAME="myapp"
export JAVA_VERSION="24-zulu"
export PROJECT_APP_VERSION=0.0.1
export PROJECT_VENDOR_NAME="vendor_name"
export GIT_AUTHOR_NAME="Default Author"
export GIT_AUTHOR_EMAIL="default@example.com"
export REMOTE_REPO_URL=""
export PROJECT_PACKAGE_NAME="core"
export PROJECT_MAIN_CLASS_NAME="App"

# Analyse des arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        -n|--name)
            APPLICATION_NAME="$2"
            shift 2
            ;;
        -p|--project)
            PROJECT_NAME="$2"
            if [[ -n "${APPLICATION_NAME}" ]]; then
               # Application's name will be project's name capitalized.
               export APPLICATION_NAME=${PROJECT_NAME^};
            fi
            shift 2
            ;;
        -j|--java)
            JAVA_VERSION="$2"
            shift 2
            ;;
        -a|--author-name)
            GIT_AUTHOR_NAME="$2"
            shift 2
            ;;
        -e|--author-email)
            GIT_AUTHOR_EMAIL="$2"
            shift 2
            ;;
        -r|--remote)
            REMOTE_REPO_URL="$2"
            shift 2
            ;;
        -pk|--package)
            PROJECT_PACKAGE_NAME="$2"
            shift 2
            ;;
        -mc|--main-class)
            PROJECT_MAIN_CLASS_NAME="$2"
            shift 2
            ;;
        -f|--frame)
            FRAME=true
            shift 1
            ;;
        -t|--template)
            APP_TEMPLATE="$2"
            shift 2
            ;;        
        -v|--version)
            PROJECT_APP_VERSION="$2"
            shift 2
            ;;
        -vd|--vendorname)
            PROJECT_VENDOR_NAME="$2"
            shift 2
            ;;
        -\?|-h|--help)
            usage
            ;;
        *)
            usage
            ;;
    esac
done

# Création du projet
mkdir -p "${PROJECT_NAME}"/{src/{{main,test}/{java,resources},docs},libs}
echo """
# README

This project is ${PROJECT_NAME} containing the application ${APPLICATION_NAME}.

by ${GIT_AUTHOR_NAME} <${GIT_AUTHOR_EMAIL}>

""" > "${PROJECT_NAME}"/README.md
echo "target/" > "${PROJECT_NAME}"/.gitignore
echo "java=${JAVA_VERSION}" > "${PROJECT_NAME}"/.sdkmanrc
curl -sL https://repo1.maven.org/maven2/org/junit/platform/junit-platform-console-standalone/1.12.2/junit-platform-console-standalone-1.12.2.jar > "${PROJECT_NAME}"/libs/junit-platform-console-standalone-1.12.2.jar
curl -sL https://gist.githubusercontent.com/mcgivrer/b95bf476b8494c180c0a386a5ae11264/raw/ > "${PROJECT_NAME}"/build

# updating build script with project details
sed -i "s/\[PROJECT_APP_NAME\]/${APPLICATION_NAME}/g" "${PROJECT_NAME}"/build
sed -i "s/\[PROJECT_APP_VERSION\]/${PROJECT_APP_VERSION}/g" "${PROJECT_NAME}"/build
sed -i "s/\[PROJECT_PACKAGE_NAME\]/${PROJECT_PACKAGE_NAME}/g" "${PROJECT_NAME}"/build
sed -i "s/\[PROJECT_MAIN_CLASS_NAME\]/${PROJECT_MAIN_CLASS_NAME}/g" "${PROJECT_NAME}"/build
sed -i "s/\[PROJECT_VENDOR_NAME\]/${PROJECT_VENDOR_NAME}/g" "${PROJECT_NAME}"/build
sed -i "s/\[GIT_AUTHOR_NAME\]/${GIT_AUTHOR_NAME}/g" "${PROJECT_NAME}"/build
sed -i "s/\[GIT_AUTHOR_EMAIL\]/${GIT_AUTHOR_EMAIL}/g" "${PROJECT_NAME}"/build

# integrate VSCode support
mkdir -p "${PROJECT_NAME}/.vscode";\
cat <<EOL > "${PROJECT_NAME}/.vscode/settings.json"
{
    "java.format.settings.url": ".vscode/java-formatter.xml",
    "java.project.sourcePaths": [
        "src/main/java",
        "src/main/resources",
        "src/test/java",
        "src/test/resources"
    ],
    "java.project.encoding": "warning",
    "java.project.referencedLibraries": [
        "libs/junit-platform-console-standalone-1.12.2.jar"
    ],
    "java.project.outputPath": "target/classes"
}
EOL

cat <<EOL > "${PROJECT_NAME}/.vscode/launch.json"
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "java",
            "name": "Current File",
            "request": "launch",
            "mainClass": "${file}"
        },
        {
            "type": "java",
            "name": "App",
            "request": "launch",
            "mainClass": "App",
            "projectName": "${PROJECT_NAME}_53c24221"
        }
    ]
}
EOL

# create documentation
cat <<EOL > "${PROJECT_NAME}"/src/docs/00-preface.md
# Project ${PROJECT_NAME}

## Preface

This is the preface for the documentation of the project ${PROJECT_NAME}.
You must rewrite this document according to your specifications.

>[!NOTE]
>Please us the markdown text format to easily create 
>docs in multiple format with the 'pandoc' tool. 

${GIT_AUTHOR_NAME} ${GIT_AUTHOR_EMAIL}
EOL

# create configuration file
cat <<EOL > "${PROJECT_NAME}"/src/main/resources/config.properties
app.debug=0
app.mode=DEVELOPMENT
EOL

# create translation file
mkdir -p "${PROJECT_NAME}"/src/main/resources/i18n
cat <<EOL > "${PROJECT_NAME}"/src/main/resources/i18n/messages.properties
app.name=${APPLICATION_NAME} (${PROJECT_APP_VERSION})
app.version=${PROJECT_APP_VERSION}
EOL

# Générer le fichier en utilisant envsubst
if [[ -n "${FRAME}" ]]; then
    cat <<EOL >> "${PROJECT_NAME}/src/main/resources/i18n/messages.properties"
app.message.welcome=Welcome into ${APPLICATION_NAME}
app.message.exit=Press the [ESCAPE] key to exit...
EOL
fi

# create a basic application class into a core package.
mkdir -p "${PROJECT_NAME}"/src/main/java/${PROJECT_PACKAGE_NAME//.//}

# Générer le fichier en utilisant envsubst
if [[ -n "${FRAME}" ]]; then
    envsubst < ~/scripts/templates/App_Frame_template.java | iconv -f UTF-8 -t UTF-8 > "${PROJECT_NAME}"/src/main/java/${PROJECT_PACKAGE_NAME//.//}/${PROJECT_MAIN_CLASS_NAME}.java

else
    envsubst < ~/scripts/templates/App_template.java | iconv -f UTF-8 -t UTF-8 > "${PROJECT_NAME}"/src/main/java/${PROJECT_PACKAGE_NAME//.//}/${PROJECT_MAIN_CLASS_NAME}.java
fi

if [[ -n "${APP_TEMPLATE}" ]]; then
    envsubst < ${APP_TEMPLATE} | iconv -f UTF-8 -t UTF-8 > "${PROJECT_NAME}"/src/main/java/${PROJECT_PACKAGE_NAME//.//}/${PROJECT_MAIN_CLASS_NAME}.java
fi

## create git repository
git init -b main --quiet "${PROJECT_NAME}"/
git -C "${PROJECT_NAME}" config user.name "${GIT_AUTHOR_NAME}"
git -C "${PROJECT_NAME}" config user.email "${GIT_AUTHOR_EMAIL}"
git -C "${PROJECT_NAME}" add .
git -C "${PROJECT_NAME}" commit -m "Create Project ${PROJECT_NAME}"

# Pousser vers le dépôt distant si l'URL est fournie
if [[ -n "${REMOTE_REPO_URL}" ]]; then
    git -C "${PROJECT_NAME}" remote add origin "${REMOTE_REPO_URL}"
    git -C "${PROJECT_NAME}" push -f origin main
fi
